service: jsonaws-btvjs-api
provider:
    name: aws
    runtime: nodejs8.10
    stage: dev
    region: us-east-1

functions:
    messages:
        handler: index.handler
        events:
            - http:
                path: /suggestions
                method: get
                cors: true

plugins:
    - serverless-offline
